/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *    
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2014 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov, Rien Quirynen, KU Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC)
 *    under supervision of Moritz Diehl. All rights reserved.
 *    
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *    
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *    
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *    
 */


#include "acado_common.h"


void acado_linear_input(const real_t* in, real_t* out)
{
const real_t* xd = in;
const real_t* u = in + 8;
/* Vector of auxiliary variables; number of elements: 8. */
real_t* a = acadoWorkspace.acado_aux;

/* Compute intermediate quantities: */
a[0] = xd[1];
a[1] = ((real_t)(-7.8182378879940003e+01)*xd[1]);
a[2] = (a[1]+((real_t)(3.7072679182320001e+00)*xd[4]));
a[3] = xd[3];
a[4] = ((real_t)(-4.0493711676430003e+01)*xd[3]);
a[5] = (a[4]+((real_t)(1.3803228073660001e+00)*xd[5]));
a[6] = u[0];
a[7] = u[1];

/* Compute outputs: */
out[0] = a[0];
out[1] = a[2];
out[2] = a[3];
out[3] = a[5];
out[4] = a[6];
out[5] = a[7];
}



void acado_rhs(const real_t* in, real_t* out)
{
const real_t* xd = in;
/* Vector of auxiliary variables; number of elements: 2. */
real_t* a = acadoWorkspace.acado_aux;

/* Compute intermediate quantities: */
a[0] = (cos(xd[6]));
a[1] = (sin(xd[6]));

/* Compute outputs: */
out[0] = xd[7];
out[1] = ((((((real_t)(0.0000000000000000e+00)-(((real_t)(-7.8182379999999995e+01)*xd[1])+((real_t)(3.7072680000000000e+00)*xd[4])))*a[0])+((real_t)(-9.8100000000000005e+00)*a[1]))-(((real_t)(2.0000000000000000e+00)*xd[7])*xd[3]))/xd[2]);
}



void acado_diffs(const real_t* in, real_t* out)
{
const real_t* xd = in;
/* Vector of auxiliary variables; number of elements: 6. */
real_t* a = acadoWorkspace.acado_aux;

/* Compute intermediate quantities: */
a[0] = (cos(xd[6]));
a[1] = ((real_t)(1.0000000000000000e+00)/xd[2]);
a[2] = (sin(xd[6]));
a[3] = (a[1]*a[1]);
a[4] = ((real_t)(-1.0000000000000000e+00)*(sin(xd[6])));
a[5] = (cos(xd[6]));

/* Compute outputs: */
out[0] = (real_t)(0.0000000000000000e+00);
out[1] = (real_t)(0.0000000000000000e+00);
out[2] = (real_t)(0.0000000000000000e+00);
out[3] = (real_t)(0.0000000000000000e+00);
out[4] = (real_t)(0.0000000000000000e+00);
out[5] = (real_t)(0.0000000000000000e+00);
out[6] = (real_t)(0.0000000000000000e+00);
out[7] = (real_t)(1.0000000000000000e+00);
out[8] = (real_t)(0.0000000000000000e+00);
out[9] = (real_t)(0.0000000000000000e+00);
out[10] = (real_t)(0.0000000000000000e+00);
out[11] = ((((real_t)(0.0000000000000000e+00)-(real_t)(-7.8182379999999995e+01))*a[0])*a[1]);
out[12] = ((real_t)(0.0000000000000000e+00)-((((((real_t)(0.0000000000000000e+00)-(((real_t)(-7.8182379999999995e+01)*xd[1])+((real_t)(3.7072680000000000e+00)*xd[4])))*a[0])+((real_t)(-9.8100000000000005e+00)*a[2]))-(((real_t)(2.0000000000000000e+00)*xd[7])*xd[3]))*a[3]));
out[13] = (((real_t)(0.0000000000000000e+00)-((real_t)(2.0000000000000000e+00)*xd[7]))*a[1]);
out[14] = ((((real_t)(0.0000000000000000e+00)-(real_t)(3.7072680000000000e+00))*a[0])*a[1]);
out[15] = (real_t)(0.0000000000000000e+00);
out[16] = (((((real_t)(0.0000000000000000e+00)-(((real_t)(-7.8182379999999995e+01)*xd[1])+((real_t)(3.7072680000000000e+00)*xd[4])))*a[4])+((real_t)(-9.8100000000000005e+00)*a[5]))*a[1]);
out[17] = (((real_t)(0.0000000000000000e+00)-((real_t)(2.0000000000000000e+00)*xd[3]))*a[1]);
out[18] = (real_t)(0.0000000000000000e+00);
out[19] = (real_t)(0.0000000000000000e+00);
}



void solve_dim4_triangular( real_t* const A, real_t* const b )
{

b[3] = b[3]/A[15];
b[2] -= + A[11]*b[3];
b[2] = b[2]/A[10];
b[1] -= + A[7]*b[3];
b[1] -= + A[6]*b[2];
b[1] = b[1]/A[5];
b[0] -= + A[3]*b[3];
b[0] -= + A[2]*b[2];
b[0] -= + A[1]*b[1];
b[0] = b[0]/A[0];
}

real_t solve_dim4_system( real_t* const A, real_t* const b, int* const rk_perm )
{
real_t det;

int i;
int j;
int k;

int indexMax;

int intSwap;

real_t valueMax;

real_t temp;

for (i = 0; i < 4; ++i)
{
rk_perm[i] = i;
}
det = 1.0000000000000000e+00;
if(fabs(A[4]) > fabs(A[0]) && fabs(A[4]) > fabs(A[8]) && fabs(A[4]) > fabs(A[12])) {
acadoWorkspace.rk_dim4_swap = A[0];
A[0] = A[4];
A[4] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[1];
A[1] = A[5];
A[5] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[2];
A[2] = A[6];
A[6] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[3];
A[3] = A[7];
A[7] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = b[0];
b[0] = b[1];
b[1] = acadoWorkspace.rk_dim4_swap;
intSwap = rk_perm[0];
rk_perm[0] = rk_perm[1];
rk_perm[1] = intSwap;
}
else if(fabs(A[8]) > fabs(A[0]) && fabs(A[8]) > fabs(A[4]) && fabs(A[8]) > fabs(A[12])) {
acadoWorkspace.rk_dim4_swap = A[0];
A[0] = A[8];
A[8] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[1];
A[1] = A[9];
A[9] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[2];
A[2] = A[10];
A[10] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[3];
A[3] = A[11];
A[11] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = b[0];
b[0] = b[2];
b[2] = acadoWorkspace.rk_dim4_swap;
intSwap = rk_perm[0];
rk_perm[0] = rk_perm[2];
rk_perm[2] = intSwap;
}
else if(fabs(A[12]) > fabs(A[0]) && fabs(A[12]) > fabs(A[4]) && fabs(A[12]) > fabs(A[8])) {
acadoWorkspace.rk_dim4_swap = A[0];
A[0] = A[12];
A[12] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[1];
A[1] = A[13];
A[13] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[2];
A[2] = A[14];
A[14] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[3];
A[3] = A[15];
A[15] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = b[0];
b[0] = b[3];
b[3] = acadoWorkspace.rk_dim4_swap;
intSwap = rk_perm[0];
rk_perm[0] = rk_perm[3];
rk_perm[3] = intSwap;
}

A[4] = -A[4]/A[0];
A[5] += + A[4]*A[1];
A[6] += + A[4]*A[2];
A[7] += + A[4]*A[3];
b[1] += + A[4]*b[0];

A[8] = -A[8]/A[0];
A[9] += + A[8]*A[1];
A[10] += + A[8]*A[2];
A[11] += + A[8]*A[3];
b[2] += + A[8]*b[0];

A[12] = -A[12]/A[0];
A[13] += + A[12]*A[1];
A[14] += + A[12]*A[2];
A[15] += + A[12]*A[3];
b[3] += + A[12]*b[0];

det = + det*A[0];

if(fabs(A[9]) > fabs(A[5]) && fabs(A[9]) > fabs(A[13])) {
acadoWorkspace.rk_dim4_swap = A[4];
A[4] = A[8];
A[8] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[5];
A[5] = A[9];
A[9] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[6];
A[6] = A[10];
A[10] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[7];
A[7] = A[11];
A[11] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = b[1];
b[1] = b[2];
b[2] = acadoWorkspace.rk_dim4_swap;
intSwap = rk_perm[1];
rk_perm[1] = rk_perm[2];
rk_perm[2] = intSwap;
}
else if(fabs(A[13]) > fabs(A[5]) && fabs(A[13]) > fabs(A[9])) {
acadoWorkspace.rk_dim4_swap = A[4];
A[4] = A[12];
A[12] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[5];
A[5] = A[13];
A[13] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[6];
A[6] = A[14];
A[14] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[7];
A[7] = A[15];
A[15] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = b[1];
b[1] = b[3];
b[3] = acadoWorkspace.rk_dim4_swap;
intSwap = rk_perm[1];
rk_perm[1] = rk_perm[3];
rk_perm[3] = intSwap;
}

A[9] = -A[9]/A[5];
A[10] += + A[9]*A[6];
A[11] += + A[9]*A[7];
b[2] += + A[9]*b[1];

A[13] = -A[13]/A[5];
A[14] += + A[13]*A[6];
A[15] += + A[13]*A[7];
b[3] += + A[13]*b[1];

det = + det*A[5];

if(fabs(A[14]) > fabs(A[10])) {
acadoWorkspace.rk_dim4_swap = A[8];
A[8] = A[12];
A[12] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[9];
A[9] = A[13];
A[13] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[10];
A[10] = A[14];
A[14] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = A[11];
A[11] = A[15];
A[15] = acadoWorkspace.rk_dim4_swap;
acadoWorkspace.rk_dim4_swap = b[2];
b[2] = b[3];
b[3] = acadoWorkspace.rk_dim4_swap;
intSwap = rk_perm[2];
rk_perm[2] = rk_perm[3];
rk_perm[3] = intSwap;
}

A[14] = -A[14]/A[10];
A[15] += + A[14]*A[11];
b[3] += + A[14]*b[2];

det = + det*A[10];

det = + det*A[15];

det = fabs(det);
solve_dim4_triangular( A, b );
return det;
}

void solve_dim4_system_reuse( real_t* const A, real_t* const b, int* const rk_perm )
{

acadoWorkspace.rk_dim4_bPerm[0] = b[rk_perm[0]];
acadoWorkspace.rk_dim4_bPerm[1] = b[rk_perm[1]];
acadoWorkspace.rk_dim4_bPerm[2] = b[rk_perm[2]];
acadoWorkspace.rk_dim4_bPerm[3] = b[rk_perm[3]];
acadoWorkspace.rk_dim4_bPerm[1] += A[4]*acadoWorkspace.rk_dim4_bPerm[0];

acadoWorkspace.rk_dim4_bPerm[2] += A[8]*acadoWorkspace.rk_dim4_bPerm[0];
acadoWorkspace.rk_dim4_bPerm[2] += A[9]*acadoWorkspace.rk_dim4_bPerm[1];

acadoWorkspace.rk_dim4_bPerm[3] += A[12]*acadoWorkspace.rk_dim4_bPerm[0];
acadoWorkspace.rk_dim4_bPerm[3] += A[13]*acadoWorkspace.rk_dim4_bPerm[1];
acadoWorkspace.rk_dim4_bPerm[3] += A[14]*acadoWorkspace.rk_dim4_bPerm[2];


solve_dim4_triangular( A, acadoWorkspace.rk_dim4_bPerm );
b[0] = acadoWorkspace.rk_dim4_bPerm[0];
b[1] = acadoWorkspace.rk_dim4_bPerm[1];
b[2] = acadoWorkspace.rk_dim4_bPerm[2];
b[3] = acadoWorkspace.rk_dim4_bPerm[3];
}



/** Matrix of size: 2 x 2 (row major format) */
static const real_t Ah_mat[ 4 ] = 
{ 5.0000000000000003e-02, 1.0773502691896258e-01, 
-7.7350269189625735e-03, 5.0000000000000003e-02 };


/* Fixed step size:0.2 */
/** Matrix of size: 12 x 12 (row major format) */
static const real_t rk_mat1[ 144 ] = 
{ 1.0000000000000000e+00, 1.0639740792605065e-02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.8663927639877781e-03, 0.0000000000000000e+00, 0.0000000000000000e+00, 3.6904169258621215e-03, 0.0000000000000000e+00, 0.0000000000000000e+00, 4.9336084450015390e-03, 0.0000000000000000e+00, 
0.0000000000000000e+00, 1.6815975416819756e-01, 0.0000000000000000e+00, 0.0000000000000000e+00, 3.9444369698729068e-02, 0.0000000000000000e+00, 0.0000000000000000e+00, -2.8852557432269554e-01, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.3681364274148991e-02, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00, 1.7591629825628969e-02, 0.0000000000000000e+00, 1.1047150446147542e-03, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0245672827922575e-02, 0.0000000000000000e+00, 3.3231524934665118e-03, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 2.8764961392249389e-01, 0.0000000000000000e+00, 2.4282127867055636e-02, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, -4.1488532142492995e-01, 0.0000000000000000e+00, 1.4142335881191636e-02, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, -2.6496001421348571e-04, 0.0000000000000000e+00, 0.0000000000000000e+00, -3.5421714943657855e-04, 0.0000000000000000e+00, 1.0000000000000000e+00, 1.0639740792605067e-02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.8663927639877786e-03, 0.0000000000000000e+00, 
0.0000000000000000e+00, 2.0715204219273024e-02, 0.0000000000000000e+00, 0.0000000000000000e+00, -9.8227776030795086e-04, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.6815975416819759e-01, 0.0000000000000000e+00, 0.0000000000000000e+00, 3.9444369698729075e-02, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, -7.3560621269882966e-04, 0.0000000000000000e+00, -2.3859161433278258e-04, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00, 1.7591629825628969e-02, 0.0000000000000000e+00, 1.1047150446147542e-03, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 2.9787425884417039e-02, 0.0000000000000000e+00, -1.0153740326283198e-03, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 2.8764961392249389e-01, 0.0000000000000000e+00, 2.4282127867055633e-02, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 };
/** Matrix of size: 48 x 2 (row major format) */
static const real_t rk_dk1[ 96 ] = 
{ 0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
-1.2036582015449815e-01, 1.8887495838747048e-01, 
9.4104861555136790e+00, -1.4766693557582128e+01, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
-1.2723570750243618e-01, 3.1743703980691096e-01, 
5.1522460545502273e+00, -1.2854203965360483e+01, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
5.3125733972878071e-02, 3.8462091938421122e-02, 
-4.4622834351045315e-01, 7.0021007378727385e-01, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
3.8424463748247269e-02, 2.3266753834427317e-02, 
-1.7562634897696178e-01, 4.3816558594822802e-01, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
6.8000012089893171e-03, 1.5121756145512000e-03, 
5.3125733972878057e-02, 3.8462091938421122e-02, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
1.0000000000000000e+00, 1.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
4.4278675380812656e-03, 8.6612343028197162e-04, 
3.8424463748247276e-02, 2.3266753834427313e-02, 
0.0000000000000000e+00, 0.0000000000000000e+00, 
1.0000000000000000e+00, 1.0000000000000000e+00 };
int integrate( real_t* const rk_eta, int resetIntegrator )
{
int error;

int i;
int j;
int k;
int run;
int run1;
int tmp_index1;
int tmp_index2;

real_t det;

acadoWorkspace.rk_ttt = 0.0000000000000000e+00;
acadoWorkspace.rk_xxx[8] = rk_eta[88];
acadoWorkspace.rk_xxx[9] = rk_eta[89];

for (run = 0; run < 1; ++run)
{
acadoWorkspace.rk_xxx[0] = rk_eta[0];
acadoWorkspace.rk_xxx[1] = rk_eta[1];
acadoWorkspace.rk_xxx[2] = rk_eta[2];
acadoWorkspace.rk_xxx[3] = rk_eta[3];
acadoWorkspace.rk_xxx[4] = rk_eta[4];
acadoWorkspace.rk_xxx[5] = rk_eta[5];
acado_linear_input( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
for (i = 0; i < 2; ++i)
{
for (run1 = 0; run1 < 6; ++run1)
{
tmp_index1 = (i * 6) + (run1);
acadoWorkspace.rk_b[tmp_index1] = acadoWorkspace.rk_rhsTemp[run1];
}
}
for (i = 0; i < 2; ++i)
{
for (run1 = 0; run1 < 6; ++run1)
{
tmp_index1 = (i * 6) + (run1);
acadoWorkspace.rk_kkk[(run1 * 2) + (i)] = + rk_mat1[tmp_index1 * 12]*acadoWorkspace.rk_b[0];
for (j = 1; j < 12; ++j)
{
acadoWorkspace.rk_kkk[(run1 * 2) + (i)] += + rk_mat1[(tmp_index1 * 12) + (j)]*acadoWorkspace.rk_b[j];
}
}
}
if( resetIntegrator ) {
for (i = 0; i < 1; ++i)
{
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 8; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
acado_diffs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 20 ]) );
for (j = 0; j < 2; ++j)
{
tmp_index1 = (run1 * 2) + (j);
acadoWorkspace.rk_A[tmp_index1 * 4] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 4 + 1] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 7)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 4) + (j)] -= 1.0000000000000000e+00;
acadoWorkspace.rk_A[tmp_index1 * 4 + 2] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 4 + 3] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 7)];
if( 1 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 4) + (j + 2)] -= 1.0000000000000000e+00;
}
acado_rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1 * 2] = acadoWorkspace.rk_kkk[run1 + 12] - acadoWorkspace.rk_rhsTemp[0];
acadoWorkspace.rk_b[run1 * 2 + 1] = acadoWorkspace.rk_kkk[run1 + 14] - acadoWorkspace.rk_rhsTemp[1];
}
det = solve_dim4_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim4_perm );
for (j = 0; j < 2; ++j)
{
acadoWorkspace.rk_kkk[j + 12] += acadoWorkspace.rk_b[j * 2];
acadoWorkspace.rk_kkk[j + 14] += acadoWorkspace.rk_b[j * 2 + 1];
}
}
}
for (i = 0; i < 5; ++i)
{
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 8; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
acado_rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1 * 2] = acadoWorkspace.rk_kkk[run1 + 12] - acadoWorkspace.rk_rhsTemp[0];
acadoWorkspace.rk_b[run1 * 2 + 1] = acadoWorkspace.rk_kkk[run1 + 14] - acadoWorkspace.rk_rhsTemp[1];
}
solve_dim4_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim4_perm );
for (j = 0; j < 2; ++j)
{
acadoWorkspace.rk_kkk[j + 12] += acadoWorkspace.rk_b[j * 2];
acadoWorkspace.rk_kkk[j + 14] += acadoWorkspace.rk_b[j * 2 + 1];
}
}
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 8; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
acado_diffs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 20 ]) );
for (j = 0; j < 2; ++j)
{
tmp_index1 = (run1 * 2) + (j);
acadoWorkspace.rk_A[tmp_index1 * 4] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 4 + 1] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 7)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 4) + (j)] -= 1.0000000000000000e+00;
acadoWorkspace.rk_A[tmp_index1 * 4 + 2] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 4 + 3] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 20) + (j * 10 + 7)];
if( 1 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 4) + (j + 2)] -= 1.0000000000000000e+00;
}
}
for (run1 = 0; run1 < 6; ++run1)
{
acadoWorkspace.rk_diffK[0] = rk_dk1[run1 * 12];
acadoWorkspace.rk_diffK[1] = rk_dk1[run1 * 12 + 1];
acadoWorkspace.rk_diffK[2] = rk_dk1[run1 * 12 + 2];
acadoWorkspace.rk_diffK[3] = rk_dk1[run1 * 12 + 3];
acadoWorkspace.rk_diffK[4] = rk_dk1[run1 * 12 + 4];
acadoWorkspace.rk_diffK[5] = rk_dk1[run1 * 12 + 5];
acadoWorkspace.rk_diffK[6] = rk_dk1[run1 * 12 + 6];
acadoWorkspace.rk_diffK[7] = rk_dk1[run1 * 12 + 7];
acadoWorkspace.rk_diffK[8] = rk_dk1[run1 * 12 + 8];
acadoWorkspace.rk_diffK[9] = rk_dk1[run1 * 12 + 9];
acadoWorkspace.rk_diffK[10] = rk_dk1[run1 * 12 + 10];
acadoWorkspace.rk_diffK[11] = rk_dk1[run1 * 12 + 11];
for (i = 0; i < 6; ++i)
{
acadoWorkspace.rk_diffsNew1[(i * 8) + (run1)] = (i == run1);
acadoWorkspace.rk_diffsNew1[(i * 8) + (run1)] += + acadoWorkspace.rk_diffK[i * 2]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_diffK[i * 2 + 1]*(real_t)1.0000000000000001e-01;
}
for (i = 0; i < 2; ++i)
{
for (j = 0; j < 6; ++j)
{
acadoWorkspace.rk_rhsTemp[j] = -(j == run1);
acadoWorkspace.rk_rhsTemp[j] -= + acadoWorkspace.rk_diffK[j * 2]*Ah_mat[i * 2];
acadoWorkspace.rk_rhsTemp[j] -= + acadoWorkspace.rk_diffK[j * 2 + 1]*Ah_mat[i * 2 + 1];
}
for (j = 0; j < 2; ++j)
{
tmp_index1 = (i * 2) + (j);
acadoWorkspace.rk_b[tmp_index1] = + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10)]*acadoWorkspace.rk_rhsTemp[0] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 1)]*acadoWorkspace.rk_rhsTemp[1] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 2)]*acadoWorkspace.rk_rhsTemp[2] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 3)]*acadoWorkspace.rk_rhsTemp[3] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 4)]*acadoWorkspace.rk_rhsTemp[4] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 5)]*acadoWorkspace.rk_rhsTemp[5];
}
}
if( 0 == run1 ) {
det = solve_dim4_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim4_perm );
}
 else {
solve_dim4_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim4_perm );
}
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i + 12] = acadoWorkspace.rk_b[i * 2];
acadoWorkspace.rk_diffK[i + 14] = acadoWorkspace.rk_b[i * 2 + 1];
}
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1)] = + acadoWorkspace.rk_diffK[i * 2 + 12]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_diffK[i * 2 + 13]*(real_t)1.0000000000000001e-01;
}
}
for (run1 = 6; run1 < 8; ++run1)
{
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_b[i * 2] = - acadoWorkspace.rk_diffsTemp2[(i * 20) + (run1)];
acadoWorkspace.rk_b[i * 2 + 1] = - acadoWorkspace.rk_diffsTemp2[(i * 20) + (run1 + 10)];
}
solve_dim4_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim4_perm );
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i + 12] = acadoWorkspace.rk_b[i * 2];
acadoWorkspace.rk_diffK[i + 14] = acadoWorkspace.rk_b[i * 2 + 1];
}
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1)] = (i == run1-6);
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1)] += + acadoWorkspace.rk_diffK[i * 2 + 12]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_diffK[i * 2 + 13]*(real_t)1.0000000000000001e-01;
}
}
for (run1 = 0; run1 < 2; ++run1)
{
acadoWorkspace.rk_diffK[0] = rk_dk1[run1 * 12 + 72];
acadoWorkspace.rk_diffK[1] = rk_dk1[run1 * 12 + 73];
acadoWorkspace.rk_diffK[2] = rk_dk1[run1 * 12 + 74];
acadoWorkspace.rk_diffK[3] = rk_dk1[run1 * 12 + 75];
acadoWorkspace.rk_diffK[4] = rk_dk1[run1 * 12 + 76];
acadoWorkspace.rk_diffK[5] = rk_dk1[run1 * 12 + 77];
acadoWorkspace.rk_diffK[6] = rk_dk1[run1 * 12 + 78];
acadoWorkspace.rk_diffK[7] = rk_dk1[run1 * 12 + 79];
acadoWorkspace.rk_diffK[8] = rk_dk1[run1 * 12 + 80];
acadoWorkspace.rk_diffK[9] = rk_dk1[run1 * 12 + 81];
acadoWorkspace.rk_diffK[10] = rk_dk1[run1 * 12 + 82];
acadoWorkspace.rk_diffK[11] = rk_dk1[run1 * 12 + 83];
for (i = 0; i < 6; ++i)
{
acadoWorkspace.rk_diffsNew1[(i * 8) + (run1 + 6)] = + acadoWorkspace.rk_diffK[i * 2]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_diffK[i * 2 + 1]*(real_t)1.0000000000000001e-01;
}
for (i = 0; i < 2; ++i)
{
for (j = 0; j < 6; ++j)
{
acadoWorkspace.rk_rhsTemp[j] = + acadoWorkspace.rk_diffK[j * 2]*Ah_mat[i * 2];
acadoWorkspace.rk_rhsTemp[j] += + acadoWorkspace.rk_diffK[j * 2 + 1]*Ah_mat[i * 2 + 1];
}
for (j = 0; j < 2; ++j)
{
tmp_index1 = (i * 2) + (j);
tmp_index2 = (run1) + (j * 10);
acadoWorkspace.rk_b[tmp_index1] = - acadoWorkspace.rk_diffsTemp2[(i * 20) + (tmp_index2 + 8)];
acadoWorkspace.rk_b[tmp_index1] -= + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10)]*acadoWorkspace.rk_rhsTemp[0] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 1)]*acadoWorkspace.rk_rhsTemp[1] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 2)]*acadoWorkspace.rk_rhsTemp[2] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 3)]*acadoWorkspace.rk_rhsTemp[3] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 4)]*acadoWorkspace.rk_rhsTemp[4] + acadoWorkspace.rk_diffsTemp2[(i * 20) + (j * 10 + 5)]*acadoWorkspace.rk_rhsTemp[5];
}
}
solve_dim4_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim4_perm );
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i + 12] = acadoWorkspace.rk_b[i * 2];
acadoWorkspace.rk_diffK[i + 14] = acadoWorkspace.rk_b[i * 2 + 1];
}
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1 + 8)] = + acadoWorkspace.rk_diffK[i * 2 + 12]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_diffK[i * 2 + 13]*(real_t)1.0000000000000001e-01;
}
}
rk_eta[0] += + acadoWorkspace.rk_kkk[0]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[1]*(real_t)1.0000000000000001e-01;
rk_eta[1] += + acadoWorkspace.rk_kkk[2]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[3]*(real_t)1.0000000000000001e-01;
rk_eta[2] += + acadoWorkspace.rk_kkk[4]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[5]*(real_t)1.0000000000000001e-01;
rk_eta[3] += + acadoWorkspace.rk_kkk[6]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[7]*(real_t)1.0000000000000001e-01;
rk_eta[4] += + acadoWorkspace.rk_kkk[8]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[9]*(real_t)1.0000000000000001e-01;
rk_eta[5] += + acadoWorkspace.rk_kkk[10]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[11]*(real_t)1.0000000000000001e-01;
rk_eta[6] += + acadoWorkspace.rk_kkk[12]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[13]*(real_t)1.0000000000000001e-01;
rk_eta[7] += + acadoWorkspace.rk_kkk[14]*(real_t)1.0000000000000001e-01 + acadoWorkspace.rk_kkk[15]*(real_t)1.0000000000000001e-01;
for (i = 0; i < 6; ++i)
{
for (j = 0; j < 6; ++j)
{
tmp_index2 = (j) + (i * 8);
rk_eta[tmp_index2 + 8] = acadoWorkspace.rk_diffsNew1[(i * 8) + (j)];
}
for (j = 0; j < 2; ++j)
{
tmp_index2 = (j) + (i * 2);
rk_eta[tmp_index2 + 72] = acadoWorkspace.rk_diffsNew1[(i * 8) + (j + 6)];
}
}
for (i = 6; i < 8; ++i)
{
for (j = 0; j < 8; ++j)
{
tmp_index2 = (j) + (i * 8);
rk_eta[tmp_index2 + 8] = acadoWorkspace.rk_diffsNew2[(i * 10-60) + (j)];
}
for (j = 0; j < 2; ++j)
{
tmp_index2 = (j) + (i * 2);
rk_eta[tmp_index2 + 72] = acadoWorkspace.rk_diffsNew2[(i * 10-60) + (j + 8)];
}
}
resetIntegrator = 0;
acadoWorkspace.rk_ttt += 1.0000000000000000e+00;
}
for (i = 0; i < 6; ++i)
{
rk_eta[i * 8 + 14] = 0.0000000000000000e+00;
rk_eta[i * 8 + 15] = 0.0000000000000000e+00;
}
for (i = 6; i < 8; ++i)
{
}
if( det < 1e-12 ) {
error = 2;
} else if( det < 1e-6 ) {
error = 1;
} else {
error = 0;
}
return error;
}



